import {
  NeetoAnalytics,
  NeetoCal,
  NeetoChangelog,
  NeetoChat,
  NeetoCourse,
  NeetoCRM,
  NeetoDesk,
  NeetoEngage,
  NeetoForm,
  NeetoGrow,
  NeetoHR,
  NeetoInvisible,
  NeetoInvoice,
  NeetoKB,
  NeetoPlanner,
  NeetoPopups,
  NeetoQuiz,
  NeetoReview,
  NeetoReplay,
  NeetoRunner,
  NeetoSite,
  NeetoStore,
  NeetoTestify,
  NeetoWireframe
} from "../icons";

export const getClientApp = (subdomain) => {
  return [
    {
      name: "Desk",
      title: NeetoDesk,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoDesk.svg",
      description: "Customer support app",
      url: {
        development: "http://spinkart.lvh.me:9001",
        staging: `https://${subdomain}.neetodesk.net`,
        production: `https://${subdomain}.neetodesk.com`,
      },
    },
    {
      name: "Chat",
      title: NeetoChat,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoChat.svg",
      description: "Customer chat app",
      url: {
        development: "http://spinkart.lvh.me:9006",
        staging: `https://${subdomain}.neetochat.net`,
        production: `https://${subdomain}.neetochat.com`,
      },
    },
    {
      name: "KB",
      title: NeetoKB,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoKB.svg",
      description: "Knowledge Base App",
      url: {
        development: "http://spinkart.lvh.me:9005/admin",
        staging: `https://${subdomain}.neetokb.net/admin`,
        production: `https://${subdomain}.neetokb.com/admin`,
      },
    },
    {
      name: "Form",
      title: NeetoForm,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoForm.svg",
      description: "Form management app",
      url: {
        development: "http://spinkart.lvh.me:9004",
        staging: `https://${subdomain}.neetoform.net`,
        production: `https://${subdomain}.neetoform.com`,
      },
    },
    {
      name: "Changelog",
      title: NeetoChangelog,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoChangelog.svg",
      description: "Changelog management app",
      url: {
        development: "http://spinkart.lvh.me:9003",
        staging: `https://${subdomain}.neetochangelog.net`,
        production: `https://${subdomain}.neetochangelog.com`,
      },
    },
    {
      name: "Invoice",
      title: NeetoInvoice,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoInvoice.svg",
      description: "Invoice management app",
      url: {
        development: "http://spinkart.lvh.me:9024",
        staging: `https://${subdomain}.neetoinvoice.net`,
        production: `https://${subdomain}.neetoinvoice.com`,
      },
    },
    {
      name: "Analytics",
      title: NeetoAnalytics,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoAnalytics.svg",
      description: "Business analytics app",
      url: {
        development: "http://spinkart.lvh.me:9007",
        staging: `https://${subdomain}.neetoanalytics.net`,
        production: `https://${subdomain}.neetoanalytics.com`,
      },
    },
    {
      name: "Engage",
      title: NeetoEngage,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoEngage.svg",
      description: "Customer engagement app",
      url: {
        development: "http://spinkart.lvh.me:9009/admin/boards",
        staging: `https://${subdomain}.neetoengage.net/admin/boards`,
        production: `https://${subdomain}.neetoengage.com/admin/boards`,
      },
    },
    {
      name: "Grow",
      title: NeetoGrow,
      icon: "",
      description: "Business grow app",
      url: {
        development: "http://spinkart.lvh.me:9010",
        staging: `https://${subdomain}.neetogrow.net`,
        production: `https://${subdomain}.neetogrow.com`,
      },
    },
    {
      name: "Quiz",
      title: NeetoQuiz,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoQuiz.svg",
      description: "Quiz app",
      url: {
        development: "http://spinkart.lvh.me:9011/quizzes",
        staging: `https://${subdomain}.neetoquiz.net/quizzes`,
        production: `https://${subdomain}.neetoquiz.com/quizzes`,
      },
    },
    {
      name: "Runner",
      title: NeetoRunner,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoRunner.svg",
      description: "Interview app",
      url: {
        development: "http://spinkart.lvh.me:9012",
        staging: `https://${subdomain}.neetorunner.net`,
        production: `https://${subdomain}.neetorunner.com`,
      },
    },
    {
      name: "Planner",
      title: NeetoPlanner,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoPlanner.svg",
      description: "Planner app",
      url: {
        development: "http://spinkart.lvh.me:9013",
        staging: `https://${subdomain}.neetoplanner.net`,
        production: `https://${subdomain}.neetoplanner.com`,
      },
    },
    {
      name: "Replay",
      title: NeetoReplay,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoReplay.svg",
      description: "Replay app",
      url: {
        development: "http://spinkart.lvh.me:9020",
        staging: `https://${subdomain}.neetoreplay.net`,
        production: `https://${subdomain}.neetoreplay.com`,
      },
    },
    {
      name: "Wireframe",
      title: NeetoWireframe,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoWireframe.svg",
      description: "Wireframe app",
      url: {
        development: "http://spinkart.lvh.me:9021",
        staging: `https://${subdomain}.neetowireframe.net`,
        production: `https://${subdomain}.neetowireframe.com`,
      },
    },
    {
      name: "Invisible",
      title: NeetoInvisible,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoInvisible.svg",
      description: "Invisible",
      url: {
        development: "http://spinkart.lvh.me:9014",
        staging: `https://${subdomain}.neetoinvisible.net`,
        production: `https://${subdomain}.neetoinvisible.com`,
      },
    },
    {
      name: "Popups",
      title: NeetoPopups,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoPopups.svg",
      description: "Popups app",
      url: {
        development: "http://spinkart.lvh.me:9021",
        staging: `https://${subdomain}.neetopopups.net`,
        production: `https://${subdomain}.neetopopups.com`,
      },
    },
    {
      name: "Store",
      title: NeetoStore,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoStore.svg",
      description: "Store app",
      url: {
        development: "http://spinkart.lvh.me:9025",
        staging: `https://${subdomain}.neetostore.net`,
        production: `https://${subdomain}.neetostore.com`,
      },
    },
    {
      name: "CRM",
      title: NeetoCRM,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoCRM.svg",
      description: "CRM app",
      url: {
        development: "http://spinkart.lvh.me:9017",
        staging: `https://${subdomain}.neetocrm.net`,
        production: `https://${subdomain}.neetocrm.com`,
      },
    },
    {
      name: "Course",
      title: NeetoCourse,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoCourse.svg",
      description: "Course app",
      url: {
        development: "http://spinkart.lvh.me:9016",
        staging: `https://${subdomain}.neetocourse.net`,
        production: `https://${subdomain}.neetocourse.com`,
      },
    },
    {
      name: "HR",
      title: NeetoHR,
      icon: "",
      description: "HR app",
      url: {
        development: "http://spinkart.lvh.me:9015",
        staging: `https://${subdomain}.neetohr.net`,
        production: `https://${subdomain}.neetohr.com`,
      },
    },
    {
      name: "Cal",
      title: NeetoCal,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoCal.svg",
      description: "Calender app",
      url: {
        development: "http://spinkart.lvh.me:9026",
        staging: `https://${subdomain}.neetocal.net`,
        production: `https://${subdomain}.neetocal.com`,
      },
    },
    {
      name: "Testify",
      title: NeetoTestify,
      icon: "",
      description: "Test management app",
      url: {
        development: "http://spinkart.lvh.me:9027",
        staging: `https://${subdomain}.neetotestify.net`,
        production: `https://${subdomain}.neetotestify.com`,
      },
    },
    {
      name: "Site",
      title: NeetoSite,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoSite.svg",
      description: "Site builder app",
      url: {
        development: "http://spinkart.lvh.me:9028",
        staging: `https://${subdomain}.neetosite.net`,
        production: `https://${subdomain}.neetosite.com`,
      },
    },
    {
      name: "Review",
      title: NeetoReview,
      icon: "https://d2v7kzglnr2dnh.cloudfront.net/icons/neetoReview.svg",
      description: "Review app builder",
      url: {
        development: "http://spinkart.lvh.me:9028",
        staging: `https://${subdomain}.neetoreview.net`,
        production: `https://${subdomain}.neetoreview.com`,
      },
    },
  ];
};
