name: Version Bumper
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Read current version
        id: CURRENT
        run: |
          IFS=',' read -r -a label_array <<< "${{ join(github.event.pull_request.labels.*.name, ',') }}"
          for item in ${label_array[*]}
          do
            if [[ "$item" == "major" || "$item" == "minor" || "$item" == "patch" ]]; then
              echo "::set-output name=VERSION::$(echo $item)"
            fi
          done
        shell: bash

      - name: Git Tagging
        id: TAGGING
        run: |
          IFS=',' read -r -a label_array <<< "${{ join(github.event.pull_request.labels.*.name, ',') }}"
          if [[ "${label_array[*]}" =~ "release" ]]; then
            echo "::set-output name=TAG_OPTION::"
          else
            echo "::set-output name=TAG_OPTION::--no-git-tag-version"
          fi

      - name: Bump Version
        run: yarn version --${{steps.CURRENT.outputs.VERSION}} ${{steps.TAGGING.outputs.TAG_OPTION}}
